title: muhanrush-Blog
description: "muhanrush Blog"
author:
  name: "muhanrush"
  email: "muhanrush@outlook.com"
  url: "https://hwjung0812.github.io"

baseurl: ""

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "muhanrush"
year : "2020"
